# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Jonathan Lau
email: laujh@ieee.org
description: > # this means to ignore newlines until "baseurl:"
  Jonathan Lau. Computer engineering student with a passion for embedded systems, scripting, and clean aesthetic interfaces.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jon-lau.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username: jon-lau
git_repo: jon-lau
github: https://github.com/jon-lau
linkedin: http://linkedin.com/in/jon-lau
projects: /projects
mail: mailto:laujh@ieee.org

include: [_data]

# Build settings
markdown: kramdown
highlighter: rouge

kramdown:
    input: GFM
    hard_wrap: false

theme: minima 
gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-avatar

exclude:
  - Gemfile
  - Gemfile.lock

# Jekyll-seo-tag config

social:
  name: Jonathan Lau
  links:
    - https://github.com/jon-lau

logo: /images/jl-icon.JPG
